/*
 Modernizr v1.6ish: miniModernizr for Isotope
 http://www.modernizr.com

 Developed by:
 - Faruk Ates  http://farukat.es/
 - Paul Irish  http://paulirish.com/

 Copyright (c) 2009-2010
 Dual-licensed under the BSD or MIT licenses.
 http://www.modernizr.com/license/
 jQuery imagesLoaded plugin v1.1.0
 http://github.com/desandro/imagesloaded

 MIT License. by Paul Irish et al.
*/

(function(m,f,q){var D=m.document,k=m.Modernizr,u=function(a){return a.charAt(0).toUpperCase()+a.slice(1)},x=["Moz","Webkit","O","Ms"],r=function(a){var b=D.documentElement.style;if("string"===typeof b[a])return a;a=u(a);for(var c=0,d=x.length;c<d;c++){var e=x[c]+a;if("string"===typeof b[e])return e}},v=r("transform"),y=r("transitionProperty");q={csstransforms:function(){return!!v},csstransforms3d:function(){var a=!!r("perspective");if(a){var a="@media ("+" -o- -moz- -ms- -webkit- -khtml- ".split(" ").join("transform-3d),(")+
"modernizr)",b=f("<style>"+a+"{#modernizr{height:3px}}</style>").appendTo("head"),c=f('<div id="modernizr" />').appendTo("html"),a=3===c.height();c.remove();b.remove()}return a},csstransitions:function(){return!!y}};var n;if(k)for(n in q)k.hasOwnProperty(n)||k.addTest(n,q[n]);else{var k=m.Modernizr={_version:"1.6ish: miniModernizr for Isotope"},z=" ";for(n in q){var A=q[n]();k[n]=A;z+=" "+(A?"":"no-")+n}f("html").addClass(z)}if(k.csstransforms){var E=k.csstransforms3d?{translate:function(a){return"translate3d("+
a[0]+"px, "+a[1]+"px, 0) "},scale:function(a){return"scale3d("+a+", "+a+", 1) "}}:{translate:function(a){return"translate("+a[0]+"px, "+a[1]+"px) "},scale:function(a){return"scale("+a+") "}},B=function(a,b,c){var d=f.data(a,"isoTransform")||{},e={},g={};e[b]=c;f.extend(d,e);for(h in d)b=d[h],g[h]=E[h](b);var h=(g.translate||"")+(g.scale||"");f.data(a,"isoTransform",d);a.style[v]=h};f.cssNumber.scale=!0;f.cssHooks.scale={set:function(a,b){B(a,"scale",b)},get:function(a,b){var c=f.data(a,"isoTransform");
return c&&c.scale?c.scale:1}};f.fx.step.scale=function(a){f.cssHooks.scale.set(a.elem,a.now+a.unit)};f.cssNumber.translate=!0;f.cssHooks.translate={set:function(a,b){B(a,"translate",b)},get:function(a,b){var c=f.data(a,"isoTransform");return c&&c.translate?c.translate:[0,0]}}}if(k.csstransitions){var F={WebkitTransitionProperty:"webkitTransitionEnd",MozTransitionProperty:"transitionend",OTransitionProperty:"oTransitionEnd otransitionend",transitionProperty:"transitionend"}[y];var G=r("transitionDuration")}var t=
f.event,H=f.event.handle?"handle":"dispatch",w;t.special.smartresize={setup:function(){f(this).bind("resize",t.special.smartresize.handler)},teardown:function(){f(this).unbind("resize",t.special.smartresize.handler)},handler:function(a,b){var c=this,d=arguments;a.type="smartresize";w&&clearTimeout(w);w=setTimeout(function(){t[H].apply(c,d)},"execAsap"===b?0:100)}};f.fn.smartresize=function(a){return a?this.bind("smartresize",a):this.trigger("smartresize",["execAsap"])};f.Isotope=function(a,b,c){this.element=
f(b);this._create(a);this._init(c)};var I=["width","height"],C=f(m);f.Isotope.settings={resizable:!0,layoutMode:"masonry",containerClass:"isotope",itemClass:"isotope-item",hiddenClass:"isotope-hidden",hiddenStyle:{opacity:0,scale:.001},visibleStyle:{opacity:1,scale:1},containerStyle:{position:"relative",overflow:"hidden"},animationEngine:"best-available",animationOptions:{queue:!1,duration:800},sortBy:"original-order",sortAscending:!0,resizesContainer:!0,transformsEnabled:!0,itemPositionDataEnabled:!1};
f.Isotope.prototype={_create:function(a){this.options=f.extend({},f.Isotope.settings,a);this.styleQueue=[];this.elemCount=0;a=this.element[0].style;this.originalStyle={};var b=I.slice(0);for(e in this.options.containerStyle)b.push(e);for(var c=0,d=b.length;c<d;c++){var e=b[c];this.originalStyle[e]=a[e]||""}this.element.css(this.options.containerStyle);this._updateAnimationEngine();this._updateUsingTransforms();this.options.getSortData=f.extend(this.options.getSortData,{"original-order":function(a,
c){c.elemCount++;return c.elemCount},random:function(){return Math.random()}});this.reloadItems();this.offset={left:parseInt(this.element.css("padding-left")||0,10),top:parseInt(this.element.css("padding-top")||0,10)};var g=this;setTimeout(function(){g.element.addClass(g.options.containerClass)},0);this.options.resizable&&C.bind("smartresize.isotope",function(){g.resize()});this.element.delegate("."+this.options.hiddenClass,"click",function(){return!1})},_getAtoms:function(a){var b=this.options.itemSelector;
a=b?a.filter(b).add(a.find(b)):a;b={position:"absolute"};a=a.filter(function(a,b){return 1===b.nodeType});this.usingTransforms&&(b.left=0,b.top=0);a.css(b).addClass(this.options.itemClass);this.updateSortData(a,!0);return a},_init:function(a){this.$filteredAtoms=this._filter(this.$allAtoms);this._sort();this.reLayout(a)},option:function(a){if(f.isPlainObject(a)){this.options=f.extend(!0,this.options,a);for(var b in a)if(a="_update"+u(b),this[a])this[a]()}},_updateAnimationEngine:function(){switch(this.options.animationEngine.toLowerCase().replace(/[ _\-]/g,
"")){case "css":case "none":var a=!1;break;case "jquery":a=!0;break;default:a=!k.csstransitions}this.isUsingJQueryAnimation=a;this._updateUsingTransforms()},_updateTransformsEnabled:function(){this._updateUsingTransforms()},_updateUsingTransforms:function(){var a=this.usingTransforms=this.options.transformsEnabled&&k.csstransforms&&k.csstransitions&&!this.isUsingJQueryAnimation;a||(delete this.options.hiddenStyle.scale,delete this.options.visibleStyle.scale);this.getPositionStyles=a?this._translate:
this._positionAbs},_filter:function(a){var b=""===this.options.filter?"*":this.options.filter;if(!b)return a;var c=this.options.hiddenClass,d="."+c,e=a.filter(d),f=e;"*"!==b&&(f=e.filter(b),d=a.not(d).not(b).addClass(c),this.styleQueue.push({$el:d,style:this.options.hiddenStyle}));this.styleQueue.push({$el:f,style:this.options.visibleStyle});f.removeClass(c);return a.filter(b)},updateSortData:function(a,b){var c=this,d=this.options.getSortData,e,g;a.each(function(){e=f(this);g={};for(var a in d)g[a]=
b||"original-order"!==a?d[a](e,c):f.data(this,"isotope-sort-data")[a];f.data(this,"isotope-sort-data",g)})},_sort:function(){var a=this.options.sortBy,b=this._getSorter,c=this.options.sortAscending?1:-1;this.$filteredAtoms.sort(function(d,e){var f=b(d,a),h=b(e,a);f===h&&"original-order"!==a&&(f=b(d,"original-order"),h=b(e,"original-order"));return(f>h?1:f<h?-1:0)*c})},_getSorter:function(a,b){return f.data(a,"isotope-sort-data")[b]},_translate:function(a,b){return{translate:[a,b]}},_positionAbs:function(a,
b){return{left:a,top:b}},_pushPosition:function(a,b,c){b=Math.round(b+this.offset.left);c=Math.round(c+this.offset.top);var d=this.getPositionStyles(b,c);this.styleQueue.push({$el:a,style:d});this.options.itemPositionDataEnabled&&a.data("isotope-item-position",{x:b,y:c})},layout:function(a,b){var c=this.options.layoutMode;this["_"+c+"Layout"](a);this.options.resizesContainer&&(c=this["_"+c+"GetContainerSize"](),this.styleQueue.push({$el:this.element,style:c}));this._processStyleQueue(a,b);this.isLaidOut=
!0},_processStyleQueue:function(a,b){var c=this.isLaidOut?this.isUsingJQueryAnimation?"animate":"css":"css",d=this.options.animationOptions,e=this.options.onLayout,g;var h=function(a,b){b.$el[c](b.style,d)};if(this._isInserting&&this.isUsingJQueryAnimation)h=function(a,b){g=b.$el.hasClass("no-transition")?"css":c;b.$el[g](b.style,d)};else if(b||e||d.complete){var l=!1,m=[b,e,d.complete],n=this;var q=!0;var r=function(){if(!l){for(var b,c=0,d=m.length;c<d;c++)b=m[c],"function"===typeof b&&b.call(n.element,
a,n);l=!0}};if(this.isUsingJQueryAnimation&&"animate"===c)d.complete=r,q=!1;else if(k.csstransitions){for(var e=0,p=this.styleQueue[0],p=p&&p.$el;!p||!p.length;){p=this.styleQueue[e++];if(!p)return;p=p.$el}0<parseFloat(getComputedStyle(p[0])[G])&&(h=function(a,b){b.$el[c](b.style,d).one(F,r)},q=!1)}}f.each(this.styleQueue,h);q&&r();this.styleQueue=[]},resize:function(){this["_"+this.options.layoutMode+"ResizeChanged"]()&&this.reLayout()},reLayout:function(a){this["_"+this.options.layoutMode+"Reset"]();
this.layout(this.$filteredAtoms,a)},addItems:function(a,b){var c=this._getAtoms(a);this.$allAtoms=this.$allAtoms.add(c);b&&b(c)},insert:function(a,b){this.element.append(a);var c=this;this.addItems(a,function(a){a=c._filter(a);c._addHideAppended(a);c._sort();c.reLayout();c._revealAppended(a,b)})},appended:function(a,b){var c=this;this.addItems(a,function(a){c._addHideAppended(a);c.layout(a);c._revealAppended(a,b)})},_addHideAppended:function(a){this.$filteredAtoms=this.$filteredAtoms.add(a);a.addClass("no-transition");
this._isInserting=!0;this.styleQueue.push({$el:a,style:this.options.hiddenStyle})},_revealAppended:function(a,b){var c=this;setTimeout(function(){a.removeClass("no-transition");c.styleQueue.push({$el:a,style:c.options.visibleStyle});c._isInserting=!1;c._processStyleQueue(a,b)},10)},reloadItems:function(){this.$allAtoms=this._getAtoms(this.element.children())},remove:function(a,b){this.$allAtoms=this.$allAtoms.not(a);this.$filteredAtoms=this.$filteredAtoms.not(a);var c=this,d=function(){a.remove();
b&&b.call(c.element)};a.filter(":not(."+this.options.hiddenClass+")").length?(this.styleQueue.push({$el:a,style:this.options.hiddenStyle}),this._sort(),this.reLayout(d)):d()},shuffle:function(a){this.updateSortData(this.$allAtoms);this.options.sortBy="random";this._sort();this.reLayout(a)},destroy:function(){var a=this.usingTransforms,b=this.options;this.$allAtoms.removeClass(b.hiddenClass+" "+b.itemClass).each(function(){var b=this.style;b.position="";b.top="";b.left="";b.opacity="";a&&(b[v]="")});
var c=this.element[0].style,d;for(d in this.originalStyle)c[d]=this.originalStyle[d];this.element.unbind(".isotope").undelegate("."+b.hiddenClass,"click").removeClass(b.containerClass).removeData("isotope");C.unbind(".isotope")},_getSegments:function(a){var b=this.options.layoutMode,c=a?"rowHeight":"columnWidth",d=a?"height":"width";a=a?"rows":"cols";var e=this.element[d](),d=this.options[b]&&this.options[b][c]||this.$filteredAtoms["outer"+u(d)](!0)||e,e=Math.floor(e/d),e=Math.max(e,1);this[b][a]=
e;this[b][c]=d},_checkIfSegmentsChanged:function(a){var b=this.options.layoutMode,c=a?"rows":"cols",d=this[b][c];this._getSegments(a);return this[b][c]!==d},_masonryReset:function(){this.masonry={};this._getSegments();var a=this.masonry.cols;for(this.masonry.colYs=[];a--;)this.masonry.colYs.push(0)},_masonryLayout:function(a){var b=this,c=b.masonry;a.each(function(){var a=f(this),e=Math.ceil(a.outerWidth(!0)/c.columnWidth),e=Math.min(e,c.cols);if(1===e)b._masonryPlaceBrick(a,c.colYs);else{var g=c.cols+
1-e,h=[],l;for(l=0;l<g;l++){var k=c.colYs.slice(l,l+e);h[l]=Math.max.apply(Math,k)}b._masonryPlaceBrick(a,h)}})},_masonryPlaceBrick:function(a,b){for(var c=Math.min.apply(Math,b),d=0,e=0,f=b.length;e<f;e++)if(b[e]===c){d=e;break}this._pushPosition(a,this.masonry.columnWidth*d,c);c+=a.outerHeight(!0);f=this.masonry.cols+1-f;for(e=0;e<f;e++)this.masonry.colYs[d+e]=c},_masonryGetContainerSize:function(){return{height:Math.max.apply(Math,this.masonry.colYs)}},_masonryResizeChanged:function(){return this._checkIfSegmentsChanged()},
_fitRowsReset:function(){this.fitRows={x:0,y:0,height:0}},_fitRowsLayout:function(a){var b=this,c=this.element.width(),d=this.fitRows;a.each(function(){var a=f(this),g=a.outerWidth(!0),h=a.outerHeight(!0);0!==d.x&&g+d.x>c&&(d.x=0,d.y=d.height);b._pushPosition(a,d.x,d.y);d.height=Math.max(d.y+h,d.height);d.x+=g})},_fitRowsGetContainerSize:function(){return{height:this.fitRows.height}},_fitRowsResizeChanged:function(){return!0},_cellsByRowReset:function(){this.cellsByRow={index:0};this._getSegments();
this._getSegments(!0)},_cellsByRowLayout:function(a){var b=this,c=this.cellsByRow;a.each(function(){var a=f(this),e=Math.floor(c.index/c.cols),g=(c.index%c.cols+.5)*c.columnWidth-a.outerWidth(!0)/2,e=(e+.5)*c.rowHeight-a.outerHeight(!0)/2;b._pushPosition(a,g,e);c.index++})},_cellsByRowGetContainerSize:function(){return{height:Math.ceil(this.$filteredAtoms.length/this.cellsByRow.cols)*this.cellsByRow.rowHeight+this.offset.top}},_cellsByRowResizeChanged:function(){return this._checkIfSegmentsChanged()},
_straightDownReset:function(){this.straightDown={y:0}},_straightDownLayout:function(a){var b=this;a.each(function(a){a=f(this);b._pushPosition(a,0,b.straightDown.y);b.straightDown.y+=a.outerHeight(!0)})},_straightDownGetContainerSize:function(){return{height:this.straightDown.y}},_straightDownResizeChanged:function(){return!0},_masonryHorizontalReset:function(){this.masonryHorizontal={};this._getSegments(!0);var a=this.masonryHorizontal.rows;for(this.masonryHorizontal.rowXs=[];a--;)this.masonryHorizontal.rowXs.push(0)},
_masonryHorizontalLayout:function(a){var b=this,c=b.masonryHorizontal;a.each(function(){var a=f(this),e=Math.ceil(a.outerHeight(!0)/c.rowHeight),e=Math.min(e,c.rows);if(1===e)b._masonryHorizontalPlaceBrick(a,c.rowXs);else{var g=c.rows+1-e,h=[],l;for(l=0;l<g;l++){var k=c.rowXs.slice(l,l+e);h[l]=Math.max.apply(Math,k)}b._masonryHorizontalPlaceBrick(a,h)}})},_masonryHorizontalPlaceBrick:function(a,b){for(var c=Math.min.apply(Math,b),d=0,e=0,f=b.length;e<f;e++)if(b[e]===c){d=e;break}this._pushPosition(a,
c,this.masonryHorizontal.rowHeight*d);c+=a.outerWidth(!0);f=this.masonryHorizontal.rows+1-f;for(e=0;e<f;e++)this.masonryHorizontal.rowXs[d+e]=c},_masonryHorizontalGetContainerSize:function(){return{width:Math.max.apply(Math,this.masonryHorizontal.rowXs)}},_masonryHorizontalResizeChanged:function(){return this._checkIfSegmentsChanged(!0)},_fitColumnsReset:function(){this.fitColumns={x:0,y:0,width:0}},_fitColumnsLayout:function(a){var b=this,c=this.element.height(),d=this.fitColumns;a.each(function(){var a=
f(this),g=a.outerWidth(!0),h=a.outerHeight(!0);0!==d.y&&h+d.y>c&&(d.x=d.width,d.y=0);b._pushPosition(a,d.x,d.y);d.width=Math.max(d.x+g,d.width);d.y+=h})},_fitColumnsGetContainerSize:function(){return{width:this.fitColumns.width}},_fitColumnsResizeChanged:function(){return!0},_cellsByColumnReset:function(){this.cellsByColumn={index:0};this._getSegments();this._getSegments(!0)},_cellsByColumnLayout:function(a){var b=this,c=this.cellsByColumn;a.each(function(){var a=f(this),e=c.index%c.rows,g=(Math.floor(c.index/
c.rows)+.5)*c.columnWidth-a.outerWidth(!0)/2,e=(e+.5)*c.rowHeight-a.outerHeight(!0)/2;b._pushPosition(a,g,e);c.index++})},_cellsByColumnGetContainerSize:function(){return{width:Math.ceil(this.$filteredAtoms.length/this.cellsByColumn.rows)*this.cellsByColumn.columnWidth}},_cellsByColumnResizeChanged:function(){return this._checkIfSegmentsChanged(!0)},_straightAcrossReset:function(){this.straightAcross={x:0}},_straightAcrossLayout:function(a){var b=this;a.each(function(a){a=f(this);b._pushPosition(a,
b.straightAcross.x,0);b.straightAcross.x+=a.outerWidth(!0)})},_straightAcrossGetContainerSize:function(){return{width:this.straightAcross.x}},_straightAcrossResizeChanged:function(){return!0}};f.fn.imagesLoaded=function(a){function b(){a.call(d,e)}function c(a){a=a.target;"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="!==a.src&&-1===f.inArray(a,h)&&(h.push(a),0>=--g&&(setTimeout(b),e.unbind(".imagesLoaded",c)))}var d=this,e=d.find("img").add(d.filter("img")),g=e.length,h=
[];g||b();e.bind("load.imagesLoaded error.imagesLoaded",c).each(function(){var a=this.src;this.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";this.src=a});return d};f.fn.isotope=function(a,b){if("string"===typeof a){var c=Array.prototype.slice.call(arguments,1);this.each(function(){var b=f.data(this,"isotope");b?f.isFunction(b[a])&&"_"!==a.charAt(0)?b[a].apply(b,c):m.console&&m.console.error("no such method '"+a+"' for isotope instance"):m.console&&m.console.error("cannot call methods on isotope prior to initialization; attempted to call method '"+
a+"'")})}else this.each(function(){var c=f.data(this,"isotope");c?(c.option(a),c._init(b)):f.data(this,"isotope",new f.Isotope(a,this,b))});return this}})(window,jQuery);